name: Benchmark

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.repository }}

      - name: Use Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Benchmark
        run: pnpm --filter="benchmarks" bench

      - name: Update README
        run: pnpm --filter="benchmarks" update-readme

      - name: Commit README.md
        run: |
          # Ignored by Renovate
          git config user.name GitHub Actions
          git config user.email github-actions@github.com
          git add -u
          git diff-index --quiet HEAD || git commit -nm "chore: updated benchmarks"
          git push
